# Generated by Django 4.0.1 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20220215_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="telegram_chat_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
